spring:
  application:
    name: sprinng-data-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/dio_db
    username: postgres
    password: 282219

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
